### ISSUE TITLE
Fix dependency

### ISSUE THREAD

**Issue by Vrakil** [butterproject/torrent-tracker-health#1]
Hello!

This library depends on [torrent-tracker](https://www.npmjs.com/package/torrent-tracker), which depends on [urijs](https://www.npmjs.com/package/urijs). torrent-tracker is using the deprecated `URIjs` instead of `urijs`. It is also connected with the dead GitLab from Popcorn Time. Do you still have access to it? 

I've pushed [torrent-tracker](https://github.com/Vrakil/torrent-tracker) with its appropriate changes. If you guys decide to fork or push, the only thing that needs to be changed is [this](https://github.com/Vrakil/torrent-tracker/blob/d7ecc1575e6719eeae8381f6c7f8d469c8ee5630/package.json#L8) line.

**Comment by streger** [comment]
It's already fixed, you can check it here https://github.com/butterproject/torrent-tracker/blob/master/package.json#L21. (You should've reported there but ok)

If you pull torrent-tracker from npm you'll see it's downloading the proper one.

**Comment by Vrakil** [comment]
Oh my, I should have seen that, sorry about this :smile:

**Comment by Vrakil** [comment]
Actually, this project is using the version from [npm](https://github.com/butterproject/torrent-tracker-health/blob/master/package.json#L14) but it should be using the one you mentioned, right?

**Comment by streger** [comment]
Both on npm and here on github should be same packages.

**Comment by Vrakil** [comment]
How can the one on npm be updated, then?

**Comment by streger** [comment]
Are you asking about process of updating or the possibility of package being different on npm?

**Comment by Vrakil** [comment]
I meant the process of updating [torrent-tracker](https://www.npmjs.com/package/torrent-tracker) using Butter's [repo](https://github.com/butterproject/torrent-tracker).

**Comment by streger** [comment]
Packages are updated like this:
https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package
ofc for any package you publish you need to be their owner on npmjs.org.

**Comment by Vrakil** [comment]
I see. Do you know who has access to the [accounts](https://www.npmjs.com/package/torrent-tracker/access) connected to it?

**Comment by streger** [comment]
We have access to both accounts.
